language: ruby
cache: bundler
sudo: required
dist: bionic
git:
  depth: 1
  submodules: false
  quiet: true
bundler_args: "--jobs=4 --retry=3 --without production"
addons: # get google-chrome-stable
  chrome: stable
  code_climate:
    repo_token: bc9e0fee3d10d7a24d762909e4fffe85dab761dfded5db6ffddf9d7b6e5b61f4
services:
  - redis
  - mysql
install:
  - bundle install -j 4 --without production
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:  
  - bundle exec rake parallel:create
  - bundle exec rake parallel:prepare
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9516 http://localhost &
script:
  - rake parallel:spec
